version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    environment:
      - db_host=postgres
      - rq_host=rabbitmq

    volumes:
      - ./api/simulation_logs:/app/logs



  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile




  postgres:
    image: postgres:14-alpine
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=metasimulator
      - POSTGRES_PASSWORD=metasimulator
      - POSTGRES_DB=metasimulator



  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api


#  schemaspy:
#    image: schemaspy/schemaspy
#    container_name: schemaspy
#    depends_on:
#      - postgres
#    volumes:
#      - ./schemaspy_output:/output
#      - ./postgresql-42.2.23.jar:/drivers/postgresql-42.2.23.jar
#    command: >
#      -t pgsql
#      -host postgres
#      -port 5432
#      -db metasimulator
#      -u metasimulator
#      -p metasimulator
#      -dp /drivers
#      -driver org.postgresql.Driver






